/* eslint-disable import/no-anonymous-default-export */
export default{
    recipes:[
        {
            id:"0",
            title:"Tarte aux fraises ",
            description:"On ne la présente plus la célèbre tarte aux fraises !! mais c'est un régal que de la manger , et forcement à la saison de ce fruit délicieux , impossible de ne pas succomber à une bonne tarte !!",
            type:"dessert",
            level:"Facile",
            servs:"8",
            prepTemp:"1h",
            cookingTemp:"30min",
            stars:"5/5",
            cost:"€",
            ingredients:[
                "Pour la pâte",
                "250 grammes de farine",
                "1 oeuf battu ",
                "50 grammes de sucre glace ",
                "45 grammes de poudre d'amande ",
                "135 grammes de beurre très froid ",
                "Pour la compote ",
                "4 pêches bien mûres ",
                "170 grammes de fraises ",
                "1 c. à soupe d'eau de fleur d'oranger ",
                "2 c. à soupe d'eau ",
                "",
                "",
                "Pour la garniture ",
                "250 grammes de fraises ",
                "quelques myrtilles",
                "1 c. à soupe d'amandes ",
                "un peu ",
                "de sucre glace",
            ],
            img:"https://img.cuisineaz.com/660x660/2017/06/07/i128107-.webp",
            instructions:[
                "Pour la pâte, mélangez la farine avec le sucre glace, la poudre d'amande dans un saladier. Ajoutez le beurre très froid. Sablez le tout du bout des doigts. Ajoutez l'oeuf. Mélangez (toujours avec les doigts) juste assez pour former une boule. La pâte colle encore un peu aux mains c'est normal. Enveloppez-la dans du film alimentaire et placez-la au frigo pour au moins une heure.",
                "Pour la compote pêches et fraises, pelez les pêches, ôtez les noyaux. Coupez la chair en morceaux et placez-les dans une casserole. Lavez, équeutez et séchez les fraises. Coupez les plus grosses en deux. Ajoutez-les aux pêches. Versez la fleur d'oranger et l'eau. Portez sur feu assez vif. Remuez régulièrement. Comptez environ 20 minutes de cuisson, la compote doit s'assécher. Quand elle a la bonne consistance, mixez-la finement avec votre mixeur plongeant. Réservez. Faites préchauffer votre four à 180°C.",
                "Beurrez et farinez un moule à tarte. Coupez la pâte en deux. Prenez-en une moitié et étalez-la finement avec un rouleau à pâtisserie votre plan de travail fariné. Garnissez-en le moule. Ôtez l'excédent de pâte. Placez une feuille de papier sulfurisé sur le fond de tarte, recouvrez de légumes secs ou de poids de cuisson. Enfournez et laissez cuire 15 minutes. Ôtez alors les poids et le papier, poursuivez la cuisson pendant 10 minutes. Sortez le plat du four et laissez-la pâte refroidir.",
                "Lavez, séchez équeutez les fraises qui servent de garniture. Coupez-les en deux )ou plus si elles sont très grosses). Lavez et séchez les myrtilles. Concassez les amandes (pas trop finement). Au moment de servir le dessert, étalez la compote sur le fond de tarte. Disposez ensuite les fraises en rosace. Répartissez les myrtilles et les amandes. Saupoudrez légèrement de sucre glace. Éventuellement, décorez aussi avec quelques petites feuilles de menthe."
            ],
        },
        {
            id:"1",
            title:"Croquettes de légumes",
            description:"Les meilleurs croquettes de ma grand-mère.",
            type:"starter",
            level:"Facile",
            servs:"6",
            prepTemp:"30min",
            cookingTemp:"25min",
            stars:"5/5",
            cost:"€",
            ingredients:[
                "1 courgette",
                "2 pommes de terre",
                "1 brocoli",
                "150 g de petits pois frais",
                "1 bouillon cube de légumes",
                "1 oeuf",
                "2 cuillère(s) à soupe de farine de pois chiche",
                "5 branches de persil frais",
                "1 cuillère(s) à soupe d'huile d'olive",
                "1/2 cuillère(s) à café de cumin en poudre",
                "sel et poivre"
            ],
            img:"https://resize-elle.ladmedia.fr/r/618,769,force,ffffff/img/var/plain_site/storage/images/elle-a-table/recettes-de-cuisine/croquettes-de-legumes-2988783/56342465-2-fre-FR/Croquettes-de-legumes.jpg",
            instructions:[
                "Pelez les pommes de terre. Détaillez le brocoli en fleurettes. Coupez grossièrement la courgette. Faites cuire tous les légumes dans un grand volume d’eau avec le bouillon-cube. 20 minutes pour les pommes de terre, 10 minutes pour le brocoli, 8 minutes pour les courgettes et les petits pois.",
                "Dans un saladier, battez l’oeuf avec la farine de pois chiche, le cumin et le persil. Salez et poivrez. Incorporez la purée de légumes.",
                "Formez de petites croquettes de légumes entre vos mains.",
                "Faites les dorer 5 minutes dans une poêle bien chaude avec l’huile d’olive."
            ],
        },
        {
            id:"2",
            title:"Pizza poulet au curry et ananas",
            description:"Pour ceux qui n'ont pas de goût ...",
            type:"main",
            level:"Facile",
            servs:"4",
            prepTemp:"20min",
            cookingTemp:"35min",
            stars:"1.5/5",
            cost:"€€€",
            ingredients:[
                "1 rouleau de pâte à pizza",
                "2 filets de poulet",
                "1 boîte de sauce tomates aux légumes",
                "1 boîte d'ananas en morceaux",
                "150 g de gruyère râpé",
                "2 c. à café de curry",
                "quelques olives",
                "huile d'olives"
            ],
            img:"https://img.cuisineaz.com/660x660/2015/05/06/i36644-pizza-poulet-au-curry-et-ananas.webp",
            instructions:[
                "Déroulez la pâte sur une plaque à pâtisserie ou à pizza, réservez-la au frigo.",
                "Préchauffez le four th.7 (210°C).",
                "Coupez en petits morceaux les blancs de poulet, saupoudrez-les du curry et mélangez bien. Faites-les revenir rapidement dans une poêle anti adhésive, réservez.",
                "Sur la pâte, étalez au pinceau 1 c. à soupe d'huile d'olive, puis la sauce tomates.",
                "Ajoutez une poignée de gruyère râpé, les morceaux de poulet et d'ananas.",
                "Finissez par un peu de gruyère râpé et quelques olives pour le décor.",
                "Enfournez pendant 20 min."
            ],
        },
        {
            id:"3",
            title:"Oeuf au plat",
            description:"Facile, rapide et pas cher, l'indémodable oeuf au plat.",
            type:"starter",
            level:"Facile",
            servs:"4",
            prepTemp:"5min",
            cookingTemp:"5min",
            stars:"3.5/5",
            cost:"€",
            ingredients:[
                "4 oeuf bien frais",
                "15g de beurre",
                "sel",
                "poivre"
            ],
            img:"https://cac.img.pmdstatic.net/fit/http.3A.2F.2Fprd2-bone-image.2Es3-website-eu-west-1.2Eamazonaws.2Ecom.2Fcac.2F2018.2F09.2F25.2Fe4927d2a-ca72-4717-8384-6c00a8b84501.2Ejpeg/748x372/quality/90/crop-from/center/oeuf-au-plat.jpeg",
            instructions:[
                "Faites fondre le beurre dans une poêle à feu moyen.",
                "Cassez délicatement les oeufs dans la poêle en prenant soin de ne pas crever le jaune. Salez et poivrez.",
                "Laissez cuire 2 à 3 min selon votre goût à feu moyen/vif : le jaune doit rester coulant et le blanc être frit.",
                "Servez immédiatement."
            ],
        },
        {
            id:"4",
            title:"Surprise du chef",
            description:"Si tu as faim, mange ta main.",
            type:"dessert",
            level:"Facile",
            servs:"4",
            prepTemp:"5min",
            cookingTemp:"5min",
            stars:"3.5/5",
            cost:"€",
            ingredients:[
                "200g de farine",
                "100g de sucre",
                "80g de beurre",
                "1 oeuf",
                "1 sachet de sucre vanillé",
                "Confiture de cerise ou confiture de framboises",
                "Amandes",
            ],
            img:"https://img.over-blog-kiwi.com/2/66/79/05/20181020/ob_fd2f69_44519364-2286055754755758-980383163563.jpg",
            instructions:[
                "Faites fondre le beurre dans une poêle à feu moyen.",
                "Cassez délicatement les oeufs dans la poêle en prenant soin de ne pas crever le jaune. Salez et poivrez.",
                "Laissez cuire 2 à 3 min selon votre goût à feu moyen/vif : le jaune doit rester coulant et le blanc être frit.",
                "Servez immédiatement."
            ],
        },
    ]
}